from fpdf import FPDF
import datetime

class PDFReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'Automated Penetration Test Report', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.cell(0, 10, 'Generated by RAIDER', 0, 1, 'C')
        self.line(10, 30, 200, 30)
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

    def chapter_title(self, label):
        self.set_font('Arial', 'B', 12)
        self.set_fill_color(200, 220, 255)
        self.cell(0, 6, f"{label}", 0, 1, 'L', 1)
        self.ln(4)

    def chapter_body(self, body):
        self.set_font('Arial', '', 10)
        self.multi_cell(0, 5, body)
        self.ln()

class Reporter:
    def __init__(self, blackboard):
        self.board = blackboard
        self.filename = f"Mission_Report_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"

    def clean_text(self, text):
        """Removes non-latin characters that might crash FPDF"""
        return text.encode('latin-1', 'replace').decode('latin-1')

    def generate_report(self):
        state = self.board.state
        pdf = PDFReport()
        pdf.add_page()
        
        pdf.chapter_title("1. Executive Summary")
        status = "CRITICAL COMPROMISE" if state['flag_captured'] else "SECURE"
        summary = f"""
        Target Host: {state['target_ip']}
        Target URL: {state['target_url']}
        Scan Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
        Final Status: {status}
        
        The Raider AI System performed an automated security assessment. 
        Total Open Ports: {len(state['ports'])}
        Total Vulnerabilities: {len(state['vulnerabilities']) + len(state['network_vulns'])}
        """
        pdf.chapter_body(summary)

        pdf.chapter_title("2. Network Intelligence")
        
        os_info = state['os_info'] if state['os_info'] != "Unknown" else "Could not fingerprint (Remote Target)"
        mac_info = state['mac_address'] if state['mac_address'] != "Unknown" else "N/A (Outside Subnet)"
        
        net_text = f"Operating System: {os_info}\nMAC Address: {mac_info}\n\nOpen Ports Detected:\n"
        for port, service in state['ports'].items():
            net_text += f" - Port {port}: {service}\n"
            
        pdf.chapter_body(self.clean_text(net_text))

        pdf.chapter_title("3. Vulnerability Findings")
        
        if not state['vulnerabilities'] and not state['network_vulns']:
            pdf.chapter_body("No significant vulnerabilities were detected.")
        else:
            if state['vulnerabilities']:
                pdf.set_font('Arial', 'B', 10)
                pdf.cell(0, 10, "Web Application Vulnerabilities:", 0, 1)
                pdf.set_font('Arial', '', 10)
                for v in state['vulnerabilities']:
                    pdf.set_text_color(200, 0, 0) # Red
                    pdf.multi_cell(0, 5, f"[CRITICAL] {self.clean_text(v)}")
                    pdf.ln(2)
                pdf.set_text_color(0, 0, 0)

            if state['network_vulns']:
                pdf.ln(5)
                pdf.set_font('Arial', 'B', 10)
                pdf.cell(0, 10, "Network Service Vulnerabilities (Nmap Scripts):", 0, 1)
                pdf.set_font('Arial', '', 10)
                for nv in state['network_vulns']:
                    pdf.multi_cell(0, 5, f" - {self.clean_text(nv)}")

        pdf.ln(10)

        pdf.add_page()
        pdf.chapter_title("4. Mission Audit Log (Timeline)")
        
        pdf.set_font('Arial', 'B', 9)
        pdf.cell(25, 7, 'Time', 1)
        pdf.cell(35, 7, 'Agent', 1)
        pdf.cell(40, 7, 'Event', 1)
        pdf.cell(0, 7, 'Details', 1, 1)
        
        pdf.set_font('Arial', '', 8)
        
        for log in state['activity_log']:
            time_str = log['time']
            source = self.clean_text(log['source'])
            event = self.clean_text(log['event'])
            details = self.clean_text(str(log['details']))[:60]
            
            pdf.cell(25, 6, time_str, 1)
            pdf.cell(35, 6, source, 1)
            pdf.cell(40, 6, event, 1)
            pdf.cell(0, 6, details, 1, 1)

        pdf.output(self.filename)
        return self.filename