from fpdf import FPDF
import datetime

class PDFReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'Automated Penetration Test Report', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.cell(0, 10, 'Generated by RAIDER', 0, 1, 'C')
        self.line(10, 30, 200, 30)
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

    def chapter_title(self, label):
        self.set_font('Arial', 'B', 12)
        self.set_fill_color(200, 220, 255)
        self.cell(0, 6, f"{label}", 0, 1, 'L', 1)
        self.ln(4)

    def chapter_body(self, body):
        self.set_font('Arial', '', 10)
        self.multi_cell(0, 5, body)
        self.ln()

class Reporter:
    def __init__(self, blackboard):
        self.board = blackboard
        self.filename = f"Mission_Report_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        
        self.nmap_explanations = {
            "http-server-header": "Version Disclosure: The server broadcasts its specific software version (e.g., Apache 2.4.x), helping attackers find specific CVEs.",
            "http-headers": "Header Analysis: Indicates potential missing security headers (like HSTS, X-Frame-Options) or information leakage in custom headers.",
            "http-methods": "Dangerous Methods: The server may allow risky HTTP methods like PUT, DELETE, or TRACE, which can lead to file uploads or cross-site tracing.",
            "http-title": "Reconnaissance Data: The page title reveals the application identity (e.g., 'Jenkins', 'Admin Dashboard'), aiding targeted attacks.",
            "http-sql-injection": "SQL Injection Risk: Automated heuristics suggest input fields on this port interact insecurely with the backend database.",
            "http-git": "Git Repository Found: The .git directory is exposed, allowing attackers to download the entire source code.",
            "ssl-cert": "SSL Certificate Info: Checks for expired certificates, weak ciphers, or self-signed certificates that facilitate Man-in-the-Middle attacks."
        }

    def clean_text(self, text):
        return text.encode('latin-1', 'replace').decode('latin-1')

    def generate_report(self):
        state = self.board.state
        pdf = PDFReport()
        pdf.add_page()
        
        pdf.chapter_title("1. Executive Summary")
        status = "CRITICAL COMPROMISE" if state['flag_captured'] else "SECURE"
        
        summary = (
            f"Target Host: {state['target_ip']}\n"
            f"Target URL: {state['target_url']}\n"
            f"Scan Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
            f"Final Status: {status}\n\n"
            f"The Raider AI System performed an automated security assessment.\n"
            f"Total Open Ports: {len(state['ports'])}\n"
            f"Total Vulnerabilities: {len(state['vulnerabilities']) + len(state['network_vulns'])}"
        )
        pdf.chapter_body(summary)

        pdf.chapter_title("2. Network Intelligence")
        
        os_info = state['os_info'] if state['os_info'] != "Unknown" else "Could not fingerprint (Remote Target)"
        mac_info = state['mac_address'] if state['mac_address'] != "Unknown" else "N/A (Outside Subnet)"
        
        net_text = f"Operating System: {os_info}\nMAC Address: {mac_info}\n\nOpen Ports Detected:\n"
        for port, service in state['ports'].items():
            net_text += f" - Port {port}: {service}\n"
            
        pdf.chapter_body(self.clean_text(net_text))

        pdf.chapter_title("3. Vulnerability Findings")
        
        if not state['vulnerabilities'] and not state['network_vulns']:
            pdf.chapter_body("No significant vulnerabilities were detected.")
        else:
            if state['vulnerabilities']:
                pdf.set_font('Arial', 'B', 10)
                pdf.cell(0, 10, "Web Application Vulnerabilities:", 0, 1)
                pdf.set_font('Arial', '', 10)
                for v in state['vulnerabilities']:
                    pdf.set_text_color(200, 0, 0) # Red
                    pdf.multi_cell(0, 5, f"[CRITICAL] {self.clean_text(v)}")
                    pdf.ln(2)
                pdf.set_text_color(0, 0, 0)

            if state['network_vulns']:
                pdf.ln(5)
                pdf.set_font('Arial', 'B', 10)
                pdf.cell(0, 10, "Network Service Vulnerabilities (Nmap Scripts):", 0, 1)
                pdf.set_font('Arial', '', 10)

                for nv in state['network_vulns']:
                    parts = nv.split('|', 1)
                    main_header = parts[0].strip()
                    detail = parts[1].strip() if len(parts) > 1 else None

                    pdf.set_text_color(0, 0, 0)
                    pdf.multi_cell(0, 5, f" - {self.clean_text(main_header)}")
                    
                    if detail:
                        pdf.set_font('Courier', '', 8)
                        pdf.set_x(15)
                        pdf.multi_cell(0, 4, f"Output: {self.clean_text(detail)}")
                        pdf.set_font('Arial', '', 10)
                    
                    try:
                        script_name = main_header.split(':')[1].strip()
                        if script_name in self.nmap_explanations:
                            pdf.set_font('Arial', 'I', 9)
                            pdf.set_text_color(80, 80, 80)
                            
                            explanation = self.nmap_explanations[script_name]
                            pdf.set_x(15)
                            pdf.multi_cell(0, 5, f"Analysis: {explanation}")
                            
                            pdf.set_font('Arial', '', 10) 
                            pdf.set_text_color(0, 0, 0)   
                            pdf.ln(1)
                    except:
                        pass
                    
                    if not detail: pdf.ln(1)

        pdf.ln(10)

        pdf.add_page()
        pdf.chapter_title("4. Mission Audit Log (Timeline)")
        
        w_time = 25
        w_agent = 35
        w_event = 40
        w_details = 90
        line_height = 6
        
        def print_table_header():
            pdf.set_font('Arial', 'B', 9)
            pdf.cell(w_time, 7, 'Time', 1)
            pdf.cell(w_agent, 7, 'Agent', 1)
            pdf.cell(w_event, 7, 'Event', 1)
            pdf.cell(0, 7, 'Details', 1, 1)
            pdf.set_font('Arial', '', 8)

        print_table_header()
        
        for log in state['activity_log']:
            time_str = log['time']
            source = self.clean_text(log['source'])
            event = self.clean_text(log['event'])
            details = self.clean_text(str(log['details']))
            
            if pdf.get_y() > 250:
                pdf.add_page()
                print_table_header()

            x_start = pdf.get_x()
            y_start = pdf.get_y()
            
            pdf.set_xy(x_start + w_time + w_agent + w_event, y_start)
            
            pdf.multi_cell(w_details, line_height, details, 1, 'L')
            
            y_end = pdf.get_y()
            row_height = y_end - y_start
            
            pdf.set_xy(x_start, y_start)
            pdf.cell(w_time, row_height, time_str, 1)
            pdf.cell(w_agent, row_height, source, 1)
            pdf.cell(w_event, row_height, event, 1)
            
            pdf.set_y(y_end)

        pdf.output(self.filename)
        return self.filename